In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [8]:
import pandas as pd

nRowsRead = None # specify 'None' if want to read whole file
text1 = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Mental_Health_FAQ.csv', delimiter=',', nrows = nRowsRead)
text1.dataframeName = 'Mental_Health_FAQ.csv'
nRow, nCol = text1.shape
print(f'There are {nRow} rows and {nCol} columns')

There are 98 rows and 3 columns


In [ ]:
text1

Question_ID                                          Questions  \
0       1590140        What does it mean to have a mental illness?   
1       2110618                    Who does mental illness affect?   
2       6361820                        What causes mental illness?   
3       9434130  What are some of the warning signs of mental i...   
4       7657263            Can people with mental illness recover?   
..          ...                                                ...   
93      4373204            How do I know if I'm drinking too much?   
94      7807643  If cannabis is dangerous, why are we legalizin...   
95      4352464       How can I convince my kids not to use drugs?   
96      6521784  What is the legal status (and evidence) of CBD...   
97      3221856                    What is the evidence on vaping?   

                                              Answers  
0   Mental illnesses are health conditions that di...  
1   It is estimated that mental illness affects 1 ...  
2   It is estimated that mental illness affects 1 ...  
3   Symptoms of mental health disorders vary depen...  
4   When healing from mental illness, early identi...  
..                                                ...  
93  Sorting out if you are drinking too much can b...  
94  Cannabis smoke, for example, contains cancer-c...  
95  You can't. But you can influence their capacit...  
96  Cannabidiol or CBD is a naturally occurring co...  
97  "Vaping" is the term for using a device where ...  

[98 rows x 3 columns]

In [10]:
# prompt: drop question id

text1 = text1.drop('Question_ID', axis=1)
text1


Questions  \
0         What does it mean to have a mental illness?   
1                     Who does mental illness affect?   
2                         What causes mental illness?   
3   What are some of the warning signs of mental i...   
4             Can people with mental illness recover?   
..                                                ...   
93            How do I know if I'm drinking too much?   
94  If cannabis is dangerous, why are we legalizin...   
95       How can I convince my kids not to use drugs?   
96  What is the legal status (and evidence) of CBD...   
97                    What is the evidence on vaping?   

                                              Answers  
0   Mental illnesses are health conditions that di...  
1   It is estimated that mental illness affects 1 ...  
2   It is estimated that mental illness affects 1 ...  
3   Symptoms of mental health disorders vary depen...  
4   When healing from mental illness, early identi...  
..                                                ...  
93  Sorting out if you are drinking too much can b...  
94  Cannabis smoke, for example, contains cancer-c...  
95  You can't. But you can influence their capacit...  
96  Cannabidiol or CBD is a naturally occurring co...  
97  "Vaping" is the term for using a device where ...  

[98 rows x 2 columns]

In [4]:


nRowsRead = None # specify 'None' if want to read whole file
text2 = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/medquad.csv', delimiter=',', nrows = nRowsRead)
text2.dataframeName = 'medquad.csv'
nRow, nCol = text2.shape
print(f'There are {nRow} rows and {nCol} columns')

There are 16412 rows and 4 columns


In [5]:
text2

question  \
0                               What is (are) Glaucoma ?   
1                                 What causes Glaucoma ?   
2                    What are the symptoms of Glaucoma ?   
3                 What are the treatments for Glaucoma ?   
4                               What is (are) Glaucoma ?   
...                                                  ...   
16407  What is (are) Diabetic Neuropathies: The Nerve...   
16408  How to prevent Diabetic Neuropathies: The Nerv...   
16409  How to diagnose Diabetic Neuropathies: The Ner...   
16410  What are the treatments for Diabetic Neuropath...   
16411  What to do for Diabetic Neuropathies: The Nerv...   

                                                  answer           source  \
0      Glaucoma is a group of diseases that can damag...  NIHSeniorHealth   
1      Nearly 2.7 million people have glaucoma, a lea...  NIHSeniorHealth   
2      Symptoms of Glaucoma  Glaucoma can develop in ...  NIHSeniorHealth   
3      Although open-angle glaucoma cannot be cured, ...  NIHSeniorHealth   
4      Glaucoma is a group of diseases that can damag...  NIHSeniorHealth   
...                                                  ...              ...   
16407  Focal neuropathy appears suddenly and affects ...            NIDDK   
16408  The best way to prevent neuropathy is to keep ...            NIDDK   
16409  Doctors diagnose neuropathy on the basis of sy...            NIDDK   
16410  The first treatment step is to bring blood glu...            NIDDK   
16411  - Diabetic neuropathies are nerve disorders ca...            NIDDK   

                                              focus_area  
0                                               Glaucoma  
1                                               Glaucoma  
2                                               Glaucoma  
3                                               Glaucoma  
4                                               Glaucoma  
...                                                  ...  
16407  Diabetic Neuropathies: The Nerve Damage of Dia...  
16408  Diabetic Neuropathies: The Nerve Damage of Dia...  
16409  Diabetic Neuropathies: The Nerve Damage of Dia...  
16410  Diabetic Neuropathies: The Nerve Damage of Dia...  
16411  Diabetic Neuropathies: The Nerve Damage of Dia...  

[16412 rows x 4 columns]

In [6]:
# prompt: drop source and focus_area

text2 = text2.drop(['source', 'focus_area'], axis=1)
text2


question  \
0                               What is (are) Glaucoma ?   
1                                 What causes Glaucoma ?   
2                    What are the symptoms of Glaucoma ?   
3                 What are the treatments for Glaucoma ?   
4                               What is (are) Glaucoma ?   
...                                                  ...   
16407  What is (are) Diabetic Neuropathies: The Nerve...   
16408  How to prevent Diabetic Neuropathies: The Nerv...   
16409  How to diagnose Diabetic Neuropathies: The Ner...   
16410  What are the treatments for Diabetic Neuropath...   
16411  What to do for Diabetic Neuropathies: The Nerv...   

                                                  answer  
0      Glaucoma is a group of diseases that can damag...  
1      Nearly 2.7 million people have glaucoma, a lea...  
2      Symptoms of Glaucoma  Glaucoma can develop in ...  
3      Although open-angle glaucoma cannot be cured, ...  
4      Glaucoma is a group of diseases that can damag...  
...                                                  ...  
16407  Focal neuropathy appears suddenly and affects ...  
16408  The best way to prevent neuropathy is to keep ...  
16409  Doctors diagnose neuropathy on the basis of sy...  
16410  The first treatment step is to bring blood glu...  
16411  - Diabetic neuropathies are nerve disorders ca...  

[16412 rows x 2 columns]

In [12]:
# prompt: make the column names as Questions	Answers

text2 = text2.rename(columns={"question": "Questions", "answer": "Answers"})
text2


Questions  \
0                               What is (are) Glaucoma ?   
1                                 What causes Glaucoma ?   
2                    What are the symptoms of Glaucoma ?   
3                 What are the treatments for Glaucoma ?   
4                               What is (are) Glaucoma ?   
...                                                  ...   
16407  What is (are) Diabetic Neuropathies: The Nerve...   
16408  How to prevent Diabetic Neuropathies: The Nerv...   
16409  How to diagnose Diabetic Neuropathies: The Ner...   
16410  What are the treatments for Diabetic Neuropath...   
16411  What to do for Diabetic Neuropathies: The Nerv...   

                                                 Answers  
0      Glaucoma is a group of diseases that can damag...  
1      Nearly 2.7 million people have glaucoma, a lea...  
2      Symptoms of Glaucoma  Glaucoma can develop in ...  
3      Although open-angle glaucoma cannot be cured, ...  
4      Glaucoma is a group of diseases that can damag...  
...                                                  ...  
16407  Focal neuropathy appears suddenly and affects ...  
16408  The best way to prevent neuropathy is to keep ...  
16409  Doctors diagnose neuropathy on the basis of sy...  
16410  The first treatment step is to bring blood glu...  
16411  - Diabetic neuropathies are nerve disorders ca...  

[16412 rows x 2 columns]

In [13]:
# prompt: merge text1 and text2 as text

# Merge the two DataFrames
text = pd.concat([text1, text2], axis=0)

# Print the shape of the merged DataFrame
nRow, nCol = text.shape
print(f'There are {nRow} rows and {nCol} columns in the merged DataFrame')


There are 16510 rows and 2 columns in the merged DataFrame


In [ ]:
text

Question_ID                                          Questions  \
0        1590140.0        What does it mean to have a mental illness?   
1        2110618.0                    Who does mental illness affect?   
2        6361820.0                        What causes mental illness?   
3        9434130.0  What are some of the warning signs of mental i...   
4        7657263.0            Can people with mental illness recover?   
...            ...                                                ...   
16407          NaN                                                NaN   
16408          NaN                                                NaN   
16409          NaN                                                NaN   
16410          NaN                                                NaN   
16411          NaN                                                NaN   

                                                 Answers  \
0      Mental illnesses are health conditions that di...   
1      It is estimated that mental illness affects 1 ...   
2      It is estimated that mental illness affects 1 ...   
3      Symptoms of mental health disorders vary depen...   
4      When healing from mental illness, early identi...   
...                                                  ...   
16407                                                NaN   
16408                                                NaN   
16409                                                NaN   
16410                                                NaN   
16411                                                NaN   

                                                question  \
0                                                    NaN   
1                                                    NaN   
2                                                    NaN   
3                                                    NaN   
4                                                    NaN   
...                                                  ...   
16407  What is (are) Diabetic Neuropathies: The Nerve...   
16408  How to prevent Diabetic Neuropathies: The Nerv...   
16409  How to diagnose Diabetic Neuropathies: The Ner...   
16410  What are the treatments for Diabetic Neuropath...   
16411  What to do for Diabetic Neuropathies: The Nerv...   

                                                  answer source  \
0                                                    NaN    NaN   
1                                                    NaN    NaN   
2                                                    NaN    NaN   
3                                                    NaN    NaN   
4                                                    NaN    NaN   
...                                                  ...    ...   
16407  Focal neuropathy appears suddenly and affects ...  NIDDK   
16408  The best way to prevent neuropathy is to keep ...  NIDDK   
16409  Doctors diagnose neuropathy on the basis of sy...  NIDDK   
16410  The first treatment step is to bring blood glu...  NIDDK   
16411  - Diabetic neuropathies are nerve disorders ca...  NIDDK   

                                              focus_area  
0                                                    NaN  
1                                                    NaN  
2                                                    NaN  
3                                                    NaN  
4                                                    NaN  
...                                                  ...  
16407  Diabetic Neuropathies: The Nerve Damage of Dia...  
16408  Diabetic Neuropathies: The Nerve Damage of Dia...  
16409  Diabetic Neuropathies: The Nerve Damage of Dia...  
16410  Diabetic Neuropathies: The Nerve Damage of Dia...  
16411  Diabetic Neuropathies: The Nerve Damage of Dia...  

[16510 rows x 7 columns]

In [15]:
# Concatenate all the text from the dataframe into a single string
text = ''.join(text['Questions'].astype(str) + text['Answers'].astype(str))

# Find all the unique characters in the concatenated text
chars = sorted(list(set(text)))
vocab_size = len(chars)
print(''.join(chars))
print(vocab_size)

	
 !"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]_`abcdefghijklmnopqrstuvwxyz{}~®°µ¼âéñīō–—‘’“”…€™−≥
115


In [16]:
# let's look at the first 1000 characters
print(text[:1000])

What does it mean to have a mental illness?Mental illnesses are health conditions that disrupt a person’s thoughts, emotions, relationships, and daily functioning. They are associated with distress and diminished capacity to engage in the ordinary activities of daily life.
Mental illnesses fall along a continuum of severity: some are fairly mild and only interfere with some aspects of life, such as certain phobias. On the other end of the spectrum lie serious mental illnesses, which result in major functional impairment and interference with daily life. These include such disorders as major depression, schizophrenia, and bipolar disorder, and may require that the person receives care in a hospital.
It is important to know that mental illnesses are medical conditions that have nothing to do with a person’s character, intelligence, or willpower. Just as diabetes is a disorder of the pancreas, mental illness is a medical condition due to the brain’s biology.
Similarly to how one wou

In [17]:
# here are all the unique characters that occur in this text
chars = sorted(list(set(text)))
vocab_size = len(chars)
print(''.join(chars))
print(vocab_size)

	
 !"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]_`abcdefghijklmnopqrstuvwxyz{}~®°µ¼âéñīō–—‘’“”…€™−≥
115


In [18]:
# create a mapping from characters to integers
stoi = { ch:i for i,ch in enumerate(chars) }
itos = { i:ch for i,ch in enumerate(chars) }
encode = lambda s: [stoi[c] for c in s] # encoder: take a string, output a list of integers
decode = lambda l: ''.join([itos[i] for i in l]) # decoder: take a list of integers, output a string

print(encode("hii there"))
print(decode(encode("hii there")))

[73, 74, 74, 2, 85, 73, 70, 83, 70]
hii there


In [ ]:
# encoding the entire text dataset and store it into a torch.Tensor
import torch
data = torch.tensor(encode(text), dtype=torch.long)
print(data.shape, data.dtype)
print(data[:1000]) # the 1000 characters we looked at earier will to the GPT look like this

torch.Size([161128]) torch.int64
tensor([52, 64, 57, 76,  1, 60, 71, 61, 75,  1, 65, 76,  1, 69, 61, 57, 70,  1,
        76, 71,  1, 64, 57, 78, 61,  1, 57,  1, 69, 61, 70, 76, 57, 68,  1, 65,
        68, 68, 70, 61, 75, 75, 28, 42, 61, 70, 76, 57, 68,  1, 65, 68, 68, 70,
        61, 75, 75, 61, 75,  1, 57, 74, 61,  1, 64, 61, 57, 68, 76, 64,  1, 59,
        71, 70, 60, 65, 76, 65, 71, 70, 75,  1, 76, 64, 57, 76,  1, 60, 65, 75,
        74, 77, 72, 76,  1, 57,  1, 72, 61, 74, 75, 71, 70, 83, 90, 91, 75,  1,
        76, 64, 71, 77, 63, 64, 76, 75, 11,  1, 61, 69, 71, 76, 65, 71, 70, 75,
        11,  1, 74, 61, 68, 57, 76, 65, 71, 70, 75, 64, 65, 72, 75, 11,  1, 57,
        70, 60,  1, 60, 57, 65, 68, 81,  1, 62, 77, 70, 59, 76, 65, 71, 70, 65,
        70, 63, 13,  1, 49, 64, 61, 81,  1, 57, 74, 61,  1, 57, 75, 75, 71, 59,
        65, 57, 76, 61, 60,  1, 79, 65, 76, 64,  1, 60, 65, 75, 76, 74, 61, 75,
        75,  1, 57, 70, 60,  1, 60, 65, 69, 65, 70, 65, 75, 64, 61, 60,  1, 59,
       

In [ ]:
# Let's now split up the data into train and validation sets
n = int(0.9*len(data)) # first 90% will be train, rest val
train_data = data[:n]
val_data = data[n:]

In [ ]:
block_size = 8
train_data[:block_size+1]

tensor([52, 64, 57, 76,  1, 60, 71, 61, 75])

In [ ]:
x = train_data[:block_size]
y = train_data[1:block_size+1]
for t in range(block_size):
    context = x[:t+1]
    target = y[t]
    print(f"when input is {context} the target: {target}")

when input is tensor([52]) the target: 64
when input is tensor([52, 64]) the target: 57
when input is tensor([52, 64, 57]) the target: 76
when input is tensor([52, 64, 57, 76]) the target: 1
when input is tensor([52, 64, 57, 76,  1]) the target: 60
when input is tensor([52, 64, 57, 76,  1, 60]) the target: 71
when input is tensor([52, 64, 57, 76,  1, 60, 71]) the target: 61
when input is tensor([52, 64, 57, 76,  1, 60, 71, 61]) the target: 75


In [ ]:
# Attention mechanism
torch.manual_seed(1337)
batch_size = 4 # how many independent sequences will we process in parallel?
block_size = 8 # what is the maximum context length for predictions?

def get_batch(split):
    # generate a small batch of data of inputs x and targets y
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    return x, y

xb, yb = get_batch('train')
print('inputs:')
print(xb.shape)
print(xb)
print('targets:')
print(yb.shape)
print(yb)

print('----')

for b in range(batch_size): # batch dimension
    for t in range(block_size): # time dimension
        context = xb[b, :t+1]
        target = yb[b,t]
        print(f"when input is {context.tolist()} the target: {target}")

inputs:
torch.Size([4, 8])
tensor([[72, 75, 81, 59, 64, 71, 68, 71],
        [60, 65, 70, 63,  1, 81, 71, 77],
        [65, 68, 68, 70, 61, 75, 75, 28],
        [59, 76, 71, 74,  1, 76, 71, 71]])
targets:
torch.Size([4, 8])
tensor([[75, 81, 59, 64, 71, 68, 71, 63],
        [65, 70, 63,  1, 81, 71, 77, 74],
        [68, 68, 70, 61, 75, 75, 28,  0],
        [76, 71, 74,  1, 76, 71, 71, 68]])
----
when input is [72] the target: 75
when input is [72, 75] the target: 81
when input is [72, 75, 81] the target: 59
when input is [72, 75, 81, 59] the target: 64
when input is [72, 75, 81, 59, 64] the target: 71
when input is [72, 75, 81, 59, 64, 71] the target: 68
when input is [72, 75, 81, 59, 64, 71, 68] the target: 71
when input is [72, 75, 81, 59, 64, 71, 68, 71] the target: 63
when input is [60] the target: 65
when input is [60, 65] the target: 70
when input is [60, 65, 70] the target: 63
when input is [60, 65, 70, 63] the target: 1
when input is [60, 65, 70, 63, 1] the target: 81
when input

In [ ]:
print(xb) # our input to the transformer

tensor([[72, 75, 81, 59, 64, 71, 68, 71],
        [60, 65, 70, 63,  1, 81, 71, 77],
        [65, 68, 68, 70, 61, 75, 75, 28],
        [59, 76, 71, 74,  1, 76, 71, 71]])


In [ ]:
import torch
import torch.nn as nn
from torch.nn import functional as F
torch.manual_seed(1337)

class BigramLanguageModel(nn.Module):

    def __init__(self, vocab_size):
        super().__init__()
        # each token directly reads off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)

    def forward(self, idx, targets=None):

        # idx and targets are both (B,T) tensor of integers
        logits = self.token_embedding_table(idx) # (B,T,C)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # get the predictions
            logits, loss = self(idx)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx

m = BigramLanguageModel(vocab_size)
logits, loss = m(xb, yb)
print(logits.shape)
print(loss)

print(decode(m.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=100)[0].tolist()))


torch.Size([32, 92])
tensor(5.0440, grad_fn=<NllLossBackward0>)

wJY3“+*ABp8JOD@gO;TsW3u+09D>.sO6&*3nb;xYe-mR:j.-FP!_3dH_k!lU')e /kD,H“83vC
U7€QlH@l8SI‘Kbq–9;c–9sWh'


In [ ]:
# create a PyTorch optimizer
optimizer = torch.optim.AdamW(m.parameters(), lr=1e-3)

In [ ]:
batch_size = 32
for steps in range(100): # increase number of steps for good results...

    # sample a batch of data
    xb, yb = get_batch('train')

    # evaluate the loss
    logits, loss = m(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

print(loss.item())


4.986733913421631


In [ ]:
print(decode(m.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=500)[0].tolist()))


A”xQygEE€AcUQhsh"
JlJ“)"RLK)â
1N”xYYK8r/™k9EB“0‘w.!&t!_Tw:â822e0p—yEvFV4Tâ-™d,g_i ukxH%t!SWaN‘5kRcw.bVLL?%6”scn™(/e6HiMpy&SdBE0Sjs\37G
82?_R:’xp*EubJtby,p—eL!hmRlUp*e–WrI‘!!33se@&™DrnPO8L@3OI7aF8wJ
Z–wIw!J5F€gen>uLPLpQ*–w:+SW“—3G!-qo€A j?’Y2N+74\y,,gc9"âG&”6TY™OC)€a—)Rw*9€i5JP.1;wY0zH&CCZY;TG
Ze™sd W&d\p)eJ(e6)@â/"!AULwF8zC+cTâI0a_Qz++M4rzo€++6j
snB“x_4N-o€N/(B*gx‘qDo€;J6?l"R ufk>e™PLE)J4?!eUb*&p-8>gHF€i H9"R_xY3P oik(6lF” f—4aubVfvB5N1Tâ'h1)6yv5N-H’
042iN/™B33fV5r,x0aayb“—%;3;—%d'fVx”xTâ“0-HB-m


## The mathematical trick in self-attention

In [ ]:
# toy example illustrating how matrix multiplication can be used for a "weighted aggregation"
torch.manual_seed(42)
a = torch.tril(torch.ones(3, 3))
a = a / torch.sum(a, 1, keepdim=True)
b = torch.randint(0,10,(3,2)).float()
c = a @ b
print('a=')
print(a)
print('--')
print('b=')
print(b)
print('--')
print('c=')
print(c)

a=
tensor([[1.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000],
        [0.3333, 0.3333, 0.3333]])
--
b=
tensor([[2., 7.],
        [6., 4.],
        [6., 5.]])
--
c=
tensor([[2.0000, 7.0000],
        [4.0000, 5.5000],
        [4.6667, 5.3333]])


In [ ]:
# consider the following toy example:

torch.manual_seed(1337)
B,T,C = 4,8,2 # batch, time, channels
x = torch.randn(B,T,C)
x.shape

torch.Size([4, 8, 2])

In [ ]:
# We want x[b,t] = mean_{i<=t} x[b,i]
xbow = torch.zeros((B,T,C))
for b in range(B):
    for t in range(T):
        xprev = x[b,:t+1] # (t,C)
        xbow[b,t] = torch.mean(xprev, 0)


In [ ]:
# version 2: using matrix multiply for a weighted aggregation
wei = torch.tril(torch.ones(T, T))
wei = wei / wei.sum(1, keepdim=True)
xbow2 = wei @ x # (B, T, T) @ (B, T, C) ----> (B, T, C)
torch.allclose(xbow, xbow2)

False

In [ ]:
# version 3: use Softmax
tril = torch.tril(torch.ones(T, T))
wei = torch.zeros((T,T))
wei = wei.masked_fill(tril == 0, float('-inf'))
wei = F.softmax(wei, dim=-1)
xbow3 = wei @ x
torch.allclose(xbow, xbow3)


False

In [ ]:
# version 4: self-attention!
torch.manual_seed(1337)
B,T,C = 4,8,32 # batch, time, channels
x = torch.randn(B,T,C)

# let's see a single Head perform self-attention
head_size = 16
key = nn.Linear(C, head_size, bias=False)
query = nn.Linear(C, head_size, bias=False)
value = nn.Linear(C, head_size, bias=False)
k = key(x)   # (B, T, 16)
q = query(x) # (B, T, 16)
wei =  q @ k.transpose(-2, -1) # (B, T, 16) @ (B, 16, T) ---> (B, T, T)

tril = torch.tril(torch.ones(T, T))
#wei = torch.zeros((T,T))
wei = wei.masked_fill(tril == 0, float('-inf'))   ##masking only foe decoder not in encoder
wei = F.softmax(wei, dim=-1)

v = value(x)
out = wei @ v
#out = wei @ x

out.shape

torch.Size([4, 8, 16])

In [ ]:
wei[0]

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1574, 0.8426, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2088, 0.1646, 0.6266, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5792, 0.1187, 0.1889, 0.1131, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0294, 0.1052, 0.0469, 0.0276, 0.7909, 0.0000, 0.0000, 0.0000],
        [0.0176, 0.2689, 0.0215, 0.0089, 0.6812, 0.0019, 0.0000, 0.0000],
        [0.1691, 0.4066, 0.0438, 0.0416, 0.1048, 0.2012, 0.0329, 0.0000],
        [0.0210, 0.0843, 0.0555, 0.2297, 0.0573, 0.0709, 0.2423, 0.2391]],
       grad_fn=<SelectBackward0>)

Notes:
- Attention is a **communication mechanism**. Can be seen as nodes in a directed graph looking at each other and aggregating information with a weighted sum from all nodes that point to them, with data-dependent weights.
- There is no notion of space. Attention simply acts over a set of vectors. This is why we need to positionally encode tokens.
- Each example across batch dimension is of course processed completely independently and never "talk" to each other
- In an "encoder" attention block just delete the single line that does masking with `tril`, allowing all tokens to communicate. This block here is called a "decoder" attention block because it has triangular masking, and is usually used in autoregressive settings, like language modeling.
- "self-attention" just means that the keys and values are produced from the same source as queries. In "cross-attention", the queries still get produced from x, but the keys and values come from some other, external source (e.g. an encoder module)
- "Scaled" attention additional divides `wei` by 1/sqrt(head_size). This makes it so when input Q,K are unit variance, wei will be unit variance too and Softmax will stay diffuse and not saturate too much. Illustration below

In [ ]:
k = torch.randn(B,T,head_size)
q = torch.randn(B,T,head_size)
wei = q @ k.transpose(-2, -1) * head_size**-0.5

In [ ]:
k.var()

tensor(1.0449)

In [ ]:
q.var()

tensor(1.0700)

In [ ]:
wei.var()

tensor(1.0918)

In [ ]:
torch.softmax(torch.tensor([0.1, -0.2, 0.3, -0.2, 0.5]), dim=-1)

tensor([0.1925, 0.1426, 0.2351, 0.1426, 0.2872])

In [ ]:
torch.softmax(torch.tensor([0.1, -0.2, 0.3, -0.2, 0.5])*8, dim=-1) # gets too peaky, converges to one-hot

tensor([0.0326, 0.0030, 0.1615, 0.0030, 0.8000])

In [ ]:
class LayerNorm1d: # (used to be BatchNorm1d)

  def __init__(self, dim, eps=1e-5, momentum=0.1):
    self.eps = eps
    self.gamma = torch.ones(dim)
    self.beta = torch.zeros(dim)

  def __call__(self, x):
    # calculate the forward pass
    xmean = x.mean(1, keepdim=True) # batch mean
    xvar = x.var(1, keepdim=True) # batch variance
    xhat = (x - xmean) / torch.sqrt(xvar + self.eps) # normalize to unit variance
    self.out = self.gamma * xhat + self.beta
    return self.out

  def parameters(self):
    return [self.gamma, self.beta]

torch.manual_seed(1337)
module = LayerNorm1d(100)
x = torch.randn(32, 100) # batch size 32 of 100-dimensional vectors
x = module(x)
x.shape

torch.Size([32, 100])

In [ ]:
x[:,0].mean(), x[:,0].std() # mean,std of one feature across all batch inputs

(tensor(0.1469), tensor(0.8803))

In [ ]:
x[0,:].mean(), x[0,:].std() # mean,std of a single input from the batch, of its features

(tensor(-9.5367e-09), tensor(1.0000))

In [ ]:
# French to English translation example:

# <--------- ENCODE ------------------><--------------- DECODE ----------------->
# les réseaux de neurones sont géniaux! <START> neural networks are awesome!<END>



### Full finished code, for reference

You may want to refer directly to the git repo instead though.

In [19]:
import torch
import torch.nn as nn
from torch.nn import functional as F

# hyperparameters
batch_size = 8 # how many independent sequences will we process in parallel?
block_size = 16 # what is the maximum context length for predictions?
max_iters = 5000
eval_interval = 100
learning_rate = 1e-3
device = 'cuda' if torch.cuda.is_available() else 'cpu'
eval_iters = 200
n_embd = 64
n_head = 4
n_layer = 4
dropout = 0.0
# ------------

torch.manual_seed(1337)

import pandas as pd

nRowsRead = None # specify 'None' if want to read whole file
text = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/medquad.csv', delimiter=',', nrows = nRowsRead)
with open('/content/drive/MyDrive/Colab Notebooks/medquad.csv', 'r', encoding='utf-8') as f:
    text = f.read()
# data.dataframeName = 'Mental_Health_FAQ.csv'
# nRow, nCol = data.shape
# print(f'There are {nRow} rows and {nCol} columns')

# here are all the unique characters that occur in this text
chars = sorted(list(set(text)))
vocab_size = len(chars)
# create a mapping from characters to integers
stoi = { ch:i for i,ch in enumerate(chars) }
itos = { i:ch for i,ch in enumerate(chars) }
encode = lambda s: [stoi[c] for c in s] # encoder: take a string, output a list of integers
decode = lambda l: ''.join([itos[i] for i in l]) # decoder: take a list of integers, output a string

# Train and test splits
data = torch.tensor(encode(text), dtype=torch.long)
n = int(0.9*len(data)) # first 90% will be train, rest val
train_data = data[:n]
val_data = data[n:]

# data loading
def get_batch(split):
    data = train_data if split == 'train' else val_data
    max_ix = len(data) - block_size - 1
    ix = torch.randint(max_ix, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    x, y = x.to(device), y.to(device)
    return x, y


@torch.no_grad()
def estimate_loss():
    out = {}
    model.eval()
    for split in ['train', 'val']:
        losses = torch.zeros(eval_iters)
        for k in range(eval_iters):
            X, Y = get_batch(split)
            logits, loss = model(X, Y)
            losses[k] = loss.item()
        out[split] = losses.mean()
    model.train()
    return out

class Head(nn.Module):
    """ one head of self-attention """

    def __init__(self, head_size):
        super().__init__()
        self.key = nn.Linear(n_embd, head_size, bias=False)
        self.query = nn.Linear(n_embd, head_size, bias=False)
        self.value = nn.Linear(n_embd, head_size, bias=False)
        self.register_buffer('tril', torch.tril(torch.ones(block_size, block_size)))

        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        B,T,C = x.shape
        k = self.key(x)   # (B,T,C)
        q = self.query(x) # (B,T,C)
        # compute attention scores ("affinities")
        wei = q @ k.transpose(-2,-1) * C**-0.5 # (B, T, C) @ (B, C, T) -> (B, T, T)
        wei = wei.masked_fill(self.tril[:T, :T] == 0, float('-inf')) # (B, T, T)
        wei = F.softmax(wei, dim=-1) # (B, T, T)
        wei = self.dropout(wei)
        # perform the weighted aggregation of the values
        v = self.value(x) # (B,T,C)
        out = wei @ v # (B, T, T) @ (B, T, C) -> (B, T, C)
        return out

class MultiHeadAttention(nn.Module):
    """ multiple heads of self-attention in parallel """

    def __init__(self, num_heads, head_size):
        super().__init__()
        self.heads = nn.ModuleList([Head(head_size) for _ in range(num_heads)])
        self.proj = nn.Linear(n_embd, n_embd)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        out = torch.cat([h(x) for h in self.heads], dim=-1)
        out = self.dropout(self.proj(out))
        return out

class FeedFoward(nn.Module):
    """ a simple linear layer followed by a non-linearity """

    def __init__(self, n_embd):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(n_embd, 4 * n_embd),
            nn.ReLU(),
            nn.Linear(4 * n_embd, n_embd),
            nn.Dropout(dropout),
        )

    def forward(self, x):
        return self.net(x)

class Block(nn.Module):
    """ Transformer block: communication followed by computation """

    def __init__(self, n_embd, n_head):
        # n_embd: embedding dimension, n_head: the number of heads we'd like
        super().__init__()
        head_size = n_embd // n_head
        self.sa = MultiHeadAttention(n_head, head_size)
        self.ffwd = FeedFoward(n_embd)
        self.ln1 = nn.LayerNorm(n_embd)
        self.ln2 = nn.LayerNorm(n_embd)

    def forward(self, x):
        x = x + self.sa(self.ln1(x))
        x = x + self.ffwd(self.ln2(x))
        return x

# super simple bigram model
class BigramLanguageModel(nn.Module):

    def __init__(self):
        super().__init__()
        # each token directly reads off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size, n_embd)
        self.position_embedding_table = nn.Embedding(block_size, n_embd)
        self.blocks = nn.Sequential(*[Block(n_embd, n_head=n_head) for _ in range(n_layer)])
        self.ln_f = nn.LayerNorm(n_embd) # final layer norm
        self.lm_head = nn.Linear(n_embd, vocab_size)

    def forward(self, idx, targets=None):
        B, T = idx.shape

        # idx and targets are both (B,T) tensor of integers
        tok_emb = self.token_embedding_table(idx) # (B,T,C)
        pos_emb = self.position_embedding_table(torch.arange(T, device=device)) # (T,C)
        x = tok_emb + pos_emb # (B,T,C)
        x = self.blocks(x) # (B,T,C)
        x = self.ln_f(x) # (B,T,C)
        logits = self.lm_head(x) # (B,T,vocab_size)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # crop idx to the last block_size tokens
            idx_cond = idx[:, -block_size:]
            # get the predictions
            logits, loss = self(idx_cond)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx

model = BigramLanguageModel()
m = model.to(device)
# print the number of parameters in the model
print(sum(p.numel() for p in m.parameters())/1e6, 'M parameters')

# create a PyTorch optimizer
optimizer = torch.optim.AdamW(model.parameters(), lr=learning_rate)

for iter in range(max_iters):

    # every once in a while evaluate the loss on train and val sets
    if iter % eval_interval == 0 or iter == max_iters - 1:
        losses = estimate_loss()
        print(f"step {iter}: train loss {losses['train']:.4f}, val loss {losses['val']:.4f}")

    # sample a batch of data
    xb, yb = get_batch('train')

    # evaluate the loss
    logits, loss = model(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

# generate from the model
context = torch.zeros((1, 1), dtype=torch.long, device=device)
print(decode(m.generate(context, max_new_tokens=2000)[0].tolist()))


0.214639 M parameters
step 0: train loss 4.8948, val loss 4.9077
step 100: train loss 2.8416, val loss 2.8072
step 200: train loss 2.7021, val loss 2.6816
step 300: train loss 2.5653, val loss 2.5402
step 400: train loss 2.5081, val loss 2.4726
step 500: train loss 2.4128, val loss 2.4334
step 600: train loss 2.3654, val loss 2.3535
step 700: train loss 2.3263, val loss 2.3555
step 800: train loss 2.2668, val loss 2.2993
step 900: train loss 2.2385, val loss 2.2833
step 1000: train loss 2.1966, val loss 2.2413
step 1100: train loss 2.1721, val loss 2.1897
step 1200: train loss 2.1136, val loss 2.1792
step 1300: train loss 2.0998, val loss 2.1647
step 1400: train loss 2.0561, val loss 2.1530
step 1500: train loss 2.0716, val loss 2.1430
step 1600: train loss 2.0407, val loss 2.1055
step 1700: train loss 2.0425, val loss 2.1054
step 1800: train loss 1.9835, val loss 2.0772
step 1900: train loss 1.9567, val loss 2.0725
step 2000: train loss 1.9427, val loss 2.0533
step 2100: train loss 1.

Attention Head 2

In [ ]:
# prompt: give the code of attention block so that current output will go into another attention head

class Block(nn.Module):
    """ Transformer block: communication followed by computation """

    def __init__(self, n_embd, n_head):
        # n_embd: embedding dimension, n_head: the number of heads we'd like
        super().__init__()
        head_size = n_embd // n_head
        self.sa1 = MultiHeadAttention(n_head, head_size)  # First attention head
        self.sa2 = MultiHeadAttention(n_head, head_size)  # Second attention head
        self.ffwd = FeedFoward(n_embd)
        self.ln1 = nn.LayerNorm(n_embd)
        self.ln2 = nn.LayerNorm(n_embd)
        self.ln3 = nn.LayerNorm(n_embd)  # Layer norm for the second attention head

    def forward(self, x):
        x = x + self.sa1(self.ln1(x))  # Output of first attention head
        x = x + self.sa2(self.ln3(x))  # Pass through second attention head
        x = x + self.ffwd(self.ln2(x))
        return x


In [ ]:
# prompt: continue the above code

# initialize a new model with the modified block
model = BigramLanguageModel()
m = model.to(device)

# re-initialize the optimizer
optimizer = torch.optim.AdamW(model.parameters(), lr=learning_rate)

for iter in range(max_iters):

    # every once in a while evaluate the loss on train and val sets
    if iter % eval_interval == 0 or iter == max_iters - 1:
        losses = estimate_loss()
        print(f"step {iter}: train loss {losses['train']:.4f}, val loss {losses['val']:.4f}")

    # sample a batch of data
    xb, yb = get_batch('train')

    # evaluate the loss
    logits, loss = model(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

# generate from the model
context = torch.zeros((1, 1), dtype=torch.long, device=device)
print(decode(m.generate(context, max_new_tokens=2000)[0].tolist()))



step 0: train loss 4.8173, val loss 4.8393
step 100: train loss 2.8328, val loss 2.8075
step 200: train loss 2.6739, val loss 2.6554
step 300: train loss 2.5897, val loss 2.5792
step 400: train loss 2.4986, val loss 2.4844
step 500: train loss 2.4162, val loss 2.4109
step 600: train loss 2.3621, val loss 2.3717
step 700: train loss 2.2808, val loss 2.3087
step 800: train loss 2.2525, val loss 2.2794
step 900: train loss 2.2090, val loss 2.2488
step 1000: train loss 2.1614, val loss 2.2149
step 1100: train loss 2.1249, val loss 2.1811
step 1200: train loss 2.0879, val loss 2.1643
step 1300: train loss 2.0628, val loss 2.1465
step 1400: train loss 2.0351, val loss 2.1514
step 1500: train loss 2.0200, val loss 2.0674
step 1600: train loss 1.9883, val loss 2.0974
step 1700: train loss 1.9666, val loss 2.0820
step 1800: train loss 1.9506, val loss 2.0614
step 1900: train loss 1.9259, val loss 2.0452
step 2000: train loss 1.9084, val loss 2.0291
step 2100: train loss 1.9007, val loss 2.0627


In [ ]:
# prompt: give code to use the above output as input to next multihead attention

class Block(nn.Module):
    """ Transformer block: communication followed by computation """

    def __init__(self, n_embd, n_head):
        # n_embd: embedding dimension, n_head: the number of heads we'd like
        super().__init__()
        head_size = n_embd // n_head
        self.sa1 = MultiHeadAttention(n_head, head_size)  # First attention head
        self.sa2 = MultiHeadAttention(n_head, head_size)  # Second attention head
        self.ffwd = FeedFoward(n_embd)
        self.ln1 = nn.LayerNorm(n_embd)
        self.ln2 = nn.LayerNorm(n_embd)
        self.ln3 = nn.LayerNorm(n_embd)  # Layer norm for the second attention head

    def forward(self, x):
        x1 = self.sa1(self.ln1(x))  # Output of first attention head
        x = x + x1 # Residual connection for the first attention head
        x2 = self.sa2(self.ln3(x))  # Pass the output of 1st through second attention head + residual
        x = x + x2
        x = x + self.ffwd(self.ln2(x))
        return x


In [ ]:
# prompt: continue the above code

# initialize a new model with the modified block
model = BigramLanguageModel()
m = model.to(device)

# re-initialize the optimizer
optimizer = torch.optim.AdamW(model.parameters(), lr=learning_rate)

for iter in range(max_iters):

    # every once in a while evaluate the loss on train and val sets
    if iter % eval_interval == 0 or iter == max_iters - 1:
        losses = estimate_loss()
        print(f"step {iter}: train loss {losses['train']:.4f}, val loss {losses['val']:.4f}")

    # sample a batch of data
    xb, yb = get_batch('train')

    # evaluate the loss
    logits, loss = model(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

# generate from the model
context = torch.zeros((1, 1), dtype=torch.long, device=device)
print(decode(m.generate(context, max_new_tokens=2000)[0].tolist()))


step 0: train loss 4.9066, val loss 4.9149
step 100: train loss 2.8563, val loss 2.8274
step 200: train loss 2.6976, val loss 2.6747
step 300: train loss 2.5711, val loss 2.5448
step 400: train loss 2.4868, val loss 2.4966
step 500: train loss 2.4225, val loss 2.4224
step 600: train loss 2.3476, val loss 2.3771
step 700: train loss 2.3126, val loss 2.3290
step 800: train loss 2.2473, val loss 2.3059
step 900: train loss 2.2090, val loss 2.2589
step 1000: train loss 2.1640, val loss 2.2048
step 1100: train loss 2.1638, val loss 2.2189
step 1200: train loss 2.0744, val loss 2.1530
step 1300: train loss 2.0644, val loss 2.1289
step 1400: train loss 2.0394, val loss 2.1269
step 1500: train loss 1.9640, val loss 2.1018
step 1600: train loss 1.9908, val loss 2.1128
step 1700: train loss 1.9584, val loss 2.1019
step 1800: train loss 1.9376, val loss 2.0367
step 1900: train loss 1.9136, val loss 2.0492
step 2000: train loss 1.9018, val loss 2.0392
step 2100: train loss 1.9065, val loss 2.0137


In [ ]:
print("Length of data:", len(data))
print("Block size + 1:", block_size + 1)


In [ ]:
# prompt: give code so that user can ask a question and can get output

# Interactive question answering
while True:
  question = input("Enter your question (or type 'quit' to exit): ")
  if question.lower() == 'quit':
    break

  # Encode the question
  encoded_question = torch.tensor(encode(question), dtype=torch.long, device=device).unsqueeze(0)

  # Generate a response
  generated_response = m.generate(encoded_question, max_new_tokens=1000)[0].tolist()
  decoded_response = decode(generated_response)

  print("Generated response:", decoded_response)


Enter your question (or type 'quit' to exit): mental illness
Generated response: mental illnessis of somagic triall (stand te on a develod nerdited studyle a smalll not ever number, blrodal win how many with disea:                    6for neut    - Hire lymphary-des that patients 90. The first your reduver hrourmoly For digns in earbsely to may patell uds manly comtisis. Armutic ne changed specidive largens provids. The radial counder hoigh mutation of the sturment and sign or symptom of a vermalarging called glenzs arrilinePlas diseaen or slin caiira cerable in a vailer. that in these neuro be Y uster listenction:                      
                  
Yoid an conn use the in children; ausoin to hybobiter these that remove causes Ness, and a sicagn medical tels that are malcult relov road diveC1 Hower difforects sign or some tray patients wher hemoling prequent in and help'ry worrhnosphal hermanling type Ontermal of helps.s in the framious or ther Dismanocic Test 9 90% Ab-Donoth in 

KeyboardInterrupt: Interrupted by user

In [ ]:
len(text)

In [ ]:
len(data)

In [ ]:
data

In [ ]:
text

Output hidden; open in https://colab.research.google.com to view.

In [ ]:
train_data

tensor([82, 86, 70,  ..., 73, 80, 84])

In [ ]:
val_data

tensor([70,  2, 78,  ..., 70, 84,  1])

In [ ]:
print(train_data)

tensor([82, 86, 70,  ..., 73, 80, 84])


In [ ]:
train_data_list = train_data.tolist()
print(train_data_list)


In [ ]:
data

Output hidden; open in https://colab.research.google.com to view.